services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: myPassword # TODO: in secrets
      POSTGRES_DB: gwent-draft-maker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile-populate-db
    container_name: php
    depends_on:
      - db

volumes:
  db_data:
