FROM php:8.3-cli

RUN apt-get update

# Install Postgre PDO
RUN apt-get install -y libpq-dev \
  && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
  && docker-php-ext-install pdo pdo_pgsql pgsql

WORKDIR /code
COPY scripts/GwentOneDB code

# CMD ["php", "./code/GwentOneDB/bin/database"]
CMD cd code && php bin/database